name: Build

on:
  pull_request:
    branches:
      - main
      - staging
      - develop

jobs:
  build:
    name: Test Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 15
      - run: npm ci
      - run: npm run build
