name: Linting

on:
  pull_request:
    branches:
      - main
      - staging
      - develop

jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 15
      - run: npm ci
      - name: ESLint
        run: node node_modules/.bin/eslint . --ext .ts
