name: Tests

on:
  pull_request:
    branches:
      - main
      - staging
      - develop

jobs:
  unit:
    name: Unit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 15
      - run: npm ci
      - name: Tests
        run: npm run test
